version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: ${DB_PGDATA}
    ports:
      - "7543:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - db

  app:
    build: src/docker/web
    volumes:
      - ./src/main:/app
      - ./allure-results/BL:/app/BL/build/allure-results
      - ./allure-results/DA:/app/DA/build/allure-results
      - ./allure-results/RestAPI:/app/RestAPI/build/allure-results
      - ./allure-results/main:/app/build/allure-results
    env_file:
      - ci.env
    working_dir: /app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - db

#  allure:
#    build: src/docker/allure
#    volumes:
#      - ./allure-results:/app/allure-results
#      - ./allure-report:/app/allure-report

networks:
  db: