version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: ${DB_PGDATA}
    volumes:
      - ./src/docker/db/init:/docker-entrypoint-initdb.d/
    ports:
      - "7543:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 5s