name: Test

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    # services:
    #   dbtest:
    #     image: postgres:latest
    #     env:
    #       POSTGRES_DB: test
    #       POSTGRES_USER: postgres
    #       POSTGRES_PASSWORD: postgres
    #     ports:
    #       - 5432:5432
    #     options: >-
    #       --health-cmd pg_isready
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 5
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'oracle'
          cache: 'gradle'

      - name: Build
        run: ./gradlew build -x test
        working-directory: src/main
