name: Test

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Install allure
        run: |
          sudo apt-get update -y
          sudo apt-get install -y default-jre
          sudo wget https://github.com/allure-framework/allure2/releases/download/2.24.1/allure_2.24.1-1_all.deb
          sudo dpkg -i allure_2.24.1-1_all.deb

      - name: Up containers
        run: docker-compose up -d

      - name: Build
        run: docker compose exec app ./gradlew build -x test

      - name: BL unit test
        run: docker compose exec app ./gradlew cleanTest :BL:test
        if: ${{ success() }}

      - name: DA unit test
        run: docker compose exec app ./gradlew cleanTest :DA:test
        if: ${{ success() }}

      - name: Integrate test
        run: docker compose exec app ./gradlew cleanTest :test
        if: ${{ success() }}

      - name: E2E test
        run: docker compose exec app ./gradlew cleanTest :RestAPI:test
        if: ${{ success() }}

      - name: Generate report
        run: |
          docker compose exec app sh -c "mkdir -p /app/res/BL && cp -R /app/BL/build/allure-results/* /app/res/BL"
          docker compose exec app sh -c "mkdir -p /app/res/DA && cp -R /app/DA/build/allure-results/* /app/res/DA"
          docker compose exec app sh -c "mkdir -p /app/res/RestAPI && cp -R /app/RestAPI/build/allure-results/* /app/res/RestAPI"
          docker compose exec app sh -c "mkdir -p /app/res/main && cp -R /app/build/allure-results/* /app/res/main"
          mkdir allure-report
          allure generate res/* --clean

      - name: Archive report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: allure-report