name: Test

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      dbtest:
        image: postgres:latest
        env:
          POSTGRES_DB: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Setup Java
        uses: oracle-actions/setup-java@v1.3.2
        with:
          version: 20

      - name: Build
        run: ./gradlew build -x test
        working-directory: src/main
